name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente para deploy (staging ou prod)'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GCP SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          version: 'latest'
          project_id: ${{ vars.PROJECT_ID }}

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials ${{ vars.CLUSTER }} --region ${{ vars.REGION }} --project ${{ vars.PROJECT_ID }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet


      - name: Deploy via Helm
        run: |
          helm upgrade --install crypto-ticker ./helm \
            --namespace ${{ github.event.inputs.environment }} \
            --set namespace=${{ github.event.inputs.environment }} \
            --set image.repository=${{ secrets.REPO }}/crypto-ticker \
            --set image.tag=latest \
            --set environment=${{ github.event.inputs.environment }}
